name: Deploy to EC2

on:
  push:
    branches:
      - qual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm dependencies
      run: |
        npm install
        npm run build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user  # Explicitly use ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
          cd /home/ec2-user/nkcng-2
          git config --global --add safe.directory /home/ec2-user/nkcng-2  # Add this
          git pull origin qual
          composer install --no-dev --optimize-autoloader --no-interaction
          npm install
          npm run build
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php-fpm
          sudo systemctl restart nginx
          sudo systemctl restart supervisord
        EOF
