name: Deploy to EC2

on:
  push:
    branches:
      - qual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Install Composer dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-interaction

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Deploy to EC2
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        echo "$ENV_FILE" > .env
        scp -i private_key -o StrictHostKeyChecking=no .env $USER@$EC2_HOST:/home/ec2-user/nkcng-2/.env
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$EC2_HOST << 'EOF'
          set -e
          cd /home/ec2-user/nkcng-2
          echo "Deploying to $(pwd)"
          sudo chgrp -R nginx .
          sudo chmod -R g+rwX .
          sudo find . -type d -exec chmod g+s {} \;
          git config --global --add safe.directory /home/ec2-user/nkcng-2
          git fetch origin qual
          git reset --hard origin/qual
          git pull origin qual
          npm ci
          npm run build
          mv public/build/.vite/manifest.json public/build/manifest.json
          composer install --no-dev --optimize-autoloader --no-interaction
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
          sudo systemctl restart php-fpm
          sudo systemctl restart nginx
          sudo systemctl restart supervisord
          echo "Deployment completed successfully"
        EOF
